<a href="https://colab.research.google.com/github/khushikayy/sklearn_library/blob/main/sklearn(5)_One_Hot_Encoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###What is Encoding in Machine Learning
Encoding in ML is the process of converting categorical data into numerical format so that algorithms can process it.

##OneHotEcoder
OneHotEncoder in sklearn is used to convert categorical data into a binary (0/1) matrix — one column for each category.

Used on: Nominal (non-ordinal) categorical features (e.g., color: red, green, blue). Purpose: Makes data usable for ML models that can't handle text labels directly

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('/content/binary_classification_sample.csv')
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,Female,HR,Bachelors,67.964728,0
1,69,31258.344158,16,Female,Engineering,High School,21.825389,0
2,46,79176.734217,4,Male,HR,PhD,94.996118,0
3,32,47699.953137,4,Male,Engineering,High School,78.634501,1
4,60,36395.191619,5,Male,Marketing,High School,8.941100,1
...,...,...,...,...,...,...,...,...
195,69,69228.805705,10,Female,Engineering,Bachelors,77.985099,1
196,30,49573.678136,14,Female,Marketing,Bachelors,3.961883,1
197,58,24253.633311,27,Female,HR,High School,48.050695,0
198,20,NaN,12,Female,Sales,High School,NaN,0
199,56,69897.075025,17,Male,Marketing,Bachelors,24.204502,0

### How to apply Ordinal Encoding

In [5]:
df.dropna(inplace = True)

In [6]:
df['Department'].value_counts()

Department
Sales          47
HR             41
Engineering    41
Marketing      40
Name: count, dtype: int64

In [7]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(drop = 'first', sparse_output=False)
df['Department'] = encoder.fit_transform(df[['Department']]).astype(int)
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,Female,1,Bachelors,67.964728,0
1,69,31258.344158,16,Female,0,High School,21.825389,0
2,46,79176.734217,4,Male,1,PhD,94.996118,0
3,32,47699.953137,4,Male,0,High School,78.634501,1
4,60,36395.191619,5,Male,0,High School,8.941100,1
...,...,...,...,...,...,...,...,...
194,44,33125.723933,13,Male,0,PhD,86.012240,1
195,69,69228.805705,10,Female,0,Bachelors,77.985099,1
196,30,49573.678136,14,Female,0,Bachelors,3.961883,1
197,58,24253.633311,27,Female,1,High School,48.050695,0
199,56,69897.075025,17,Male,0,Bachelors,24.204502,0

In [11]:
# One-hot encoding
cols = ['Department']
encoder = OneHotEncoder(drop='first',sparse_output=False)

encoded_col = encoder.fit_transform(df[cols]).astype(int)
encoded_df = pd.DataFrame(encoded_col, columns=encoder.get_feature_names_out(cols))

# Align indexes
encoded_df.index = df.index

# Concatenate
final_df = pd.concat([df,encoded_df], axis=1)

In [12]:
final_df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased,Department_1
0,56,51905.183591,27,Female,1,Bachelors,67.964728,0,1
1,69,31258.344158,16,Female,0,High School,21.825389,0,0
2,46,79176.734217,4,Male,1,PhD,94.996118,0,1
3,32,47699.953137,4,Male,0,High School,78.634501,1,0
4,60,36395.191619,5,Male,0,High School,8.941100,1,0
...,...,...,...,...,...,...,...,...,...
194,44,33125.723933,13,Male,0,PhD,86.012240,1,0
195,69,69228.805705,10,Female,0,Bachelors,77.985099,1,0
196,30,49573.678136,14,Female,0,Bachelors,3.961883,1,0
197,58,24253.633311,27,Female,1,High School,48.050695,0,1
199,56,69897.075025,17,Male,0,Bachelors,24.204502,0,0