<a href="https://colab.research.google.com/github/khushikayy/sklearn_library/blob/main/sklearn(4)_label_ordinal_encoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Label Encoding and Ordinal Encoding are both techniques used to convert categorical text data into numbers

Ordinal Encoding converts categorical columns into integers while assuming a specific ordered relationship between the categories.

Label Encoding converts categorical values into integers, but it treats them as purely unique identifiers without implying any order.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df= pd.read_csv('/content/CAR DETAILS FROM CAR DEKHO.csv',usecols=['name','fuel','seller_type','transmission','owner'])

In [ ]:
df.head()

                       name    fuel seller_type transmission         owner
0             Maruti 800 AC  Petrol  Individual       Manual   First Owner
1  Maruti Wagon R LXI Minor  Petrol  Individual       Manual   First Owner
2      Hyundai Verna 1.6 SX  Diesel  Individual       Manual   First Owner
3    Datsun RediGO T Option  Petrol  Individual       Manual   First Owner
4     Honda Amaze VX i-DTEC  Diesel  Individual       Manual  Second Owner

###To summarize:
ordinal variables --> OrdinalEncoder:Owner,Seller_type,Transmission

Target or label variables---> LabelEncoder: Fuel

### Using python

In [ ]:
df.drop('name', axis=1, inplace=True)

In [ ]:
# df['transmission'] = df['transmission'].map({'Manual':0, 'Automatic':1})

In [ ]:
# df['seller_type'] = df['seller_type'].map({'Individual':0, 'Dealer':1, 'Trustmark Dealer':2})

In [ ]:
# df.sample(5)

In [ ]:
# df['transmission'].apply(lambda x: 1 if x=='Manual' else 0)

In [ ]:
df

        fuel seller_type transmission         owner
0     Petrol  Individual       Manual   First Owner
1     Petrol  Individual       Manual   First Owner
2     Diesel  Individual       Manual   First Owner
3     Petrol  Individual       Manual   First Owner
4     Diesel  Individual       Manual  Second Owner
...      ...         ...          ...           ...
4335  Diesel  Individual       Manual  Second Owner
4336  Diesel  Individual       Manual  Second Owner
4337  Petrol  Individual       Manual  Second Owner
4338  Diesel  Individual       Manual   First Owner
4339  Petrol  Individual       Manual   First Owner

[4340 rows x 4 columns]

### using Scikitlearn

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('fuel',axis=1),df['fuel'],test_size=0.33, random_state=42)

In [ ]:
X_train

     seller_type transmission        owner
3679  Individual       Manual  Third Owner
2093      Dealer    Automatic  First Owner
3220  Individual       Manual  First Owner
2422  Individual       Manual  First Owner
1867  Individual       Manual  Third Owner
...          ...          ...          ...
3444  Individual       Manual  First Owner
466   Individual       Manual  First Owner
3092      Dealer       Manual  First Owner
3772  Individual       Manual  First Owner
860   Individual       Manual  First Owner

[2907 rows x 3 columns]

In [ ]:
y_train

3679    Diesel
2093    Petrol
3220    Petrol
2422    Diesel
1867    Petrol
         ...
3444    Diesel
466     Diesel
3092    Diesel
3772    Diesel
860     Petrol
Name: fuel, Length: 2907, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

###1. Applying Label Encoder
Recommended to use at categories under variables of output (y_train,y_test)

In [ ]:
le = LabelEncoder()

In [ ]:
y_train_scaled = le.fit_transform(y_train)
y_test_scaled = le.transform(y_test)

In [ ]:
y_test_scaled

array([1, 4, 4, ..., 1, 1, 4])

In [ ]:
X_train

     seller_type transmission        owner
3679  Individual       Manual  Third Owner
2093      Dealer    Automatic  First Owner
3220  Individual       Manual  First Owner
2422  Individual       Manual  First Owner
1867  Individual       Manual  Third Owner
...          ...          ...          ...
3444  Individual       Manual  First Owner
466   Individual       Manual  First Owner
3092      Dealer       Manual  First Owner
3772  Individual       Manual  First Owner
860   Individual       Manual  First Owner

[2907 rows x 3 columns]

### 2. Applying Ordinal Encoder

In [ ]:
oe = OrdinalEncoder()
X_train_traf = oe.fit_transform(X_train)
X_test_traf = oe.transform(X_test)

In [ ]:
X_train.head()

     seller_type transmission        owner
3679  Individual       Manual  Third Owner
2093      Dealer    Automatic  First Owner
3220  Individual       Manual  First Owner
2422  Individual       Manual  First Owner
1867  Individual       Manual  Third Owner

In [ ]:
X_train_traf

array([[1., 1., 4.],
       [0., 0., 0.],
       [1., 1., 0.],
       ...,
       [0., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])